/**
 * 日本全国47都道府県の多言語対応データ
 * Complete Japanese Prefecture Data with 20-language support
 */

export interface Prefecture {
  code: string;
  region: string;
  names: Record<string, string>;
}

// 全47都道府県の定義
export const ALL_PREFECTURES: Prefecture[] = [
  // 北海道地方 (Hokkaido Region)
  {
    code: 'hokkaido',
    region: 'hokkaido',
    names: {
      ja: '北海道',
      en: 'Hokkaido',
      'zh-cn': '北海道',
      'zh-tw': '北海道',
      ko: '홋카이도',
      th: 'ฮอกไกโด',
      vi: 'Hokkaido',
      id: 'Hokkaido',
      ms: 'Hokkaido',
      tl: 'Hokkaido',
      fr: 'Hokkaido',
      de: 'Hokkaido',
      es: 'Hokkaido',
      it: 'Hokkaido',
      pt: 'Hokkaido',
      ru: 'Хоккайдо',
      ar: 'هوكايدو',
      hi: 'होक्काइडो',
      tr: 'Hokkaido',
      'pt-br': 'Hokkaido'
    }
  },

  // 東北地方 (Tohoku Region)
  {
    code: 'aomori',
    region: 'tohoku',
    names: {
      ja: '青森県',
      en: 'Aomori Prefecture',
      'zh-cn': '青森县',
      'zh-tw': '青森縣',
      ko: '아오모리현',
      th: 'จังหวัดอาโอโมริ',
      vi: 'Tỉnh Aomori',
      id: 'Prefektur Aomori',
      ms: 'Wilayah Aomori',
      tl: 'Prepektura ng Aomori',
      fr: 'Préfecture d\'Aomori',
      de: 'Präfektur Aomori',
      es: 'Prefectura de Aomori',
      it: 'Prefettura di Aomori',
      pt: 'Prefeitura de Aomori',
      ru: 'Префектура Аомори',
      ar: 'محافظة أوموري',
      hi: 'आओमोरी प्रान्त',
      tr: 'Aomori Eyaleti',
      'pt-br': 'Prefeitura de Aomori'
    }
  },
  {
    code: 'iwate',
    region: 'tohoku',
    names: {
      ja: '岩手県',
      en: 'Iwate Prefecture',
      'zh-cn': '岩手县',
      'zh-tw': '岩手縣',
      ko: '이와테현',
      th: 'จังหวัดอิวาเตะ',
      vi: 'Tỉnh Iwate',
      id: 'Prefektur Iwate',
      ms: 'Wilayah Iwate',
      tl: 'Prepektura ng Iwate',
      fr: 'Préfecture d\'Iwate',
      de: 'Präfektur Iwate',
      es: 'Prefectura de Iwate',
      it: 'Prefettura di Iwate',
      pt: 'Prefeitura de Iwate',
      ru: 'Префектура Ивате',
      ar: 'محافظة إواته',
      hi: 'इवाते प्रान्त',
      tr: 'Iwate Eyaleti',
      'pt-br': 'Prefeitura de Iwate'
    }
  },
  {
    code: 'miyagi',
    region: 'tohoku',
    names: {
      ja: '宮城県',
      en: 'Miyagi Prefecture',
      'zh-cn': '宫城县',
      'zh-tw': '宮城縣',
      ko: '미야기현',
      th: 'จังหวัดมิยางิ',
      vi: 'Tỉnh Miyagi',
      id: 'Prefektur Miyagi',
      ms: 'Wilayah Miyagi',
      tl: 'Prepektura ng Miyagi',
      fr: 'Préfecture de Miyagi',
      de: 'Präfektur Miyagi',
      es: 'Prefectura de Miyagi',
      it: 'Prefettura di Miyagi',
      pt: 'Prefeitura de Miyagi',
      ru: 'Префектура Мияги',
      ar: 'محافظة مياغي',
      hi: 'मियागी प्रान्त',
      tr: 'Miyagi Eyaleti',
      'pt-br': 'Prefeitura de Miyagi'
    }
  },
  {
    code: 'akita',
    region: 'tohoku',
    names: {
      ja: '秋田県',
      en: 'Akita Prefecture',
      'zh-cn': '秋田县',
      'zh-tw': '秋田縣',
      ko: '아키타현',
      th: 'จังหวัดอากิตะ',
      vi: 'Tỉnh Akita',
      id: 'Prefektur Akita',
      ms: 'Wilayah Akita',
      tl: 'Prepektura ng Akita',
      fr: 'Préfecture d\'Akita',
      de: 'Präfektur Akita',
      es: 'Prefectura de Akita',
      it: 'Prefettura di Akita',
      pt: 'Prefeitura de Akita',
      ru: 'Префектура Акита',
      ar: 'محافظة أكيتا',
      hi: 'अकिता प्रान्त',
      tr: 'Akita Eyaleti',
      'pt-br': 'Prefeitura de Akita'
    }
  },
  {
    code: 'yamagata',
    region: 'tohoku',
    names: {
      ja: '山形県',
      en: 'Yamagata Prefecture',
      'zh-cn': '山形县',
      'zh-tw': '山形縣',
      ko: '야마가타현',
      th: 'จังหวัดยามางาตะ',
      vi: 'Tỉnh Yamagata',
      id: 'Prefektur Yamagata',
      ms: 'Wilayah Yamagata',
      tl: 'Prepektura ng Yamagata',
      fr: 'Préfecture de Yamagata',
      de: 'Präfektur Yamagata',
      es: 'Prefectura de Yamagata',
      it: 'Prefettura di Yamagata',
      pt: 'Prefeitura de Yamagata',
      ru: 'Префектура Ямагата',
      ar: 'محافظة ياماغاتا',
      hi: 'यामागाता प्रान्त',
      tr: 'Yamagata Eyaleti',
      'pt-br': 'Prefeitura de Yamagata'
    }
  },
  {
    code: 'fukushima',
    region: 'tohoku',
    names: {
      ja: '福島県',
      en: 'Fukushima Prefecture',
      'zh-cn': '福岛县',
      'zh-tw': '福島縣',
      ko: '후쿠시마현',
      th: 'จังหวัดฟุกุชิมะ',
      vi: 'Tỉnh Fukushima',
      id: 'Prefektur Fukushima',
      ms: 'Wilayah Fukushima',
      tl: 'Prepektura ng Fukushima',
      fr: 'Préfecture de Fukushima',
      de: 'Präfektur Fukushima',
      es: 'Prefectura de Fukushima',
      it: 'Prefettura di Fukushima',
      pt: 'Prefeitura de Fukushima',
      ru: 'Префектура Фукусима',
      ar: 'محافظة فوكوشيما',
      hi: 'फुकुशिमा प्रान्त',
      tr: 'Fukushima Eyaleti',
      'pt-br': 'Prefeitura de Fukushima'
    }
  },

  // 関東地方 (Kanto Region)
  {
    code: 'ibaraki',
    region: 'kanto',
    names: {
      ja: '茨城県',
      en: 'Ibaraki Prefecture',
      'zh-cn': '茨城县',
      'zh-tw': '茨城縣',
      ko: '이바라키현',
      th: 'จังหวัดอิบารากิ',
      vi: 'Tỉnh Ibaraki',
      id: 'Prefektur Ibaraki',
      ms: 'Wilayah Ibaraki',
      tl: 'Prepektura ng Ibaraki',
      fr: 'Préfecture d\'Ibaraki',
      de: 'Präfektur Ibaraki',
      es: 'Prefectura de Ibaraki',
      it: 'Prefettura di Ibaraki',
      pt: 'Prefeitura de Ibaraki',
      ru: 'Префектура Ибараки',
      ar: 'محافظة إباراكي',
      hi: 'इबाराकी प्रान्त',
      tr: 'Ibaraki Eyaleti',
      'pt-br': 'Prefeitura de Ibaraki'
    }
  },
  {
    code: 'tochigi',
    region: 'kanto',
    names: {
      ja: '栃木県',
      en: 'Tochigi Prefecture',
      'zh-cn': '栃木县',
      'zh-tw': '栃木縣',
      ko: '도치기현',
      th: 'จังหวัดโทชิงิ',
      vi: 'Tỉnh Tochigi',
      id: 'Prefektur Tochigi',
      ms: 'Wilayah Tochigi',
      tl: 'Prepektura ng Tochigi',
      fr: 'Préfecture de Tochigi',
      de: 'Präfektur Tochigi',
      es: 'Prefectura de Tochigi',
      it: 'Prefettura di Tochigi',
      pt: 'Prefeitura de Tochigi',
      ru: 'Префектура Точиги',
      ar: 'محافظة توتشيغي',
      hi: 'तोचिगी प्रान्त',
      tr: 'Tochigi Eyaleti',
      'pt-br': 'Prefeitura de Tochigi'
    }
  },
  {
    code: 'gunma',
    region: 'kanto',
    names: {
      ja: '群馬県',
      en: 'Gunma Prefecture',
      'zh-cn': '群马县',
      'zh-tw': '群馬縣',
      ko: '군마현',
      th: 'จังหวัดกุนมะ',
      vi: 'Tỉnh Gunma',
      id: 'Prefektur Gunma',
      ms: 'Wilayah Gunma',
      tl: 'Prepektura ng Gunma',
      fr: 'Préfecture de Gunma',
      de: 'Präfektur Gunma',
      es: 'Prefectura de Gunma',
      it: 'Prefettura di Gunma',
      pt: 'Prefeitura de Gunma',
      ru: 'Префектура Гумма',
      ar: 'محافظة غونما',
      hi: 'गुन्मा प्रान्त',
      tr: 'Gunma Eyaleti',
      'pt-br': 'Prefeitura de Gunma'
    }
  },
  {
    code: 'saitama',
    region: 'kanto',
    names: {
      ja: '埼玉県',
      en: 'Saitama Prefecture',
      'zh-cn': '埼玉县',
      'zh-tw': '埼玉縣',
      ko: '사이타마현',
      th: 'จังหวัดไซตามะ',
      vi: 'Tỉnh Saitama',
      id: 'Prefektur Saitama',
      ms: 'Wilayah Saitama',
      tl: 'Prepektura ng Saitama',
      fr: 'Préfecture de Saitama',
      de: 'Präfektur Saitama',
      es: 'Prefectura de Saitama',
      it: 'Prefettura di Saitama',
      pt: 'Prefeitura de Saitama',
      ru: 'Префектура Сайтама',
      ar: 'محافظة سايتاما',
      hi: 'सैतामा प्रान्त',
      tr: 'Saitama Eyaleti',
      'pt-br': 'Prefeitura de Saitama'
    }
  },
  {
    code: 'chiba',
    region: 'kanto',
    names: {
      ja: '千葉県',
      en: 'Chiba Prefecture',
      'zh-cn': '千叶县',
      'zh-tw': '千葉縣',
      ko: '치바현',
      th: 'จังหวัดชิบะ',
      vi: 'Tỉnh Chiba',
      id: 'Prefektur Chiba',
      ms: 'Wilayah Chiba',
      tl: 'Prepektura ng Chiba',
      fr: 'Préfecture de Chiba',
      de: 'Präfektur Chiba',
      es: 'Prefectura de Chiba',
      it: 'Prefettura di Chiba',
      pt: 'Prefeitura de Chiba',
      ru: 'Префектура Тиба',
      ar: 'محافظة تشيبا',
      hi: 'चिबा प्रान्त',
      tr: 'Chiba Eyaleti',
      'pt-br': 'Prefeitura de Chiba'
    }
  },
  {
    code: 'tokyo',
    region: 'kanto',
    names: {
      ja: '東京都',
      en: 'Tokyo Metropolis',
      'zh-cn': '东京都',
      'zh-tw': '東京都',
      ko: '도쿄도',
      th: 'โตเกียว',
      vi: 'Thủ đô Tokyo',
      id: 'Metropolis Tokyo',
      ms: 'Metropolitan Tokyo',
      tl: 'Lungsod ng Tokyo',
      fr: 'Métropole de Tokyo',
      de: 'Metropole Tokyo',
      es: 'Metrópolis de Tokio',
      it: 'Metropoli di Tokyo',
      pt: 'Metrópole de Tóquio',
      ru: 'Токио',
      ar: 'طوكيو',
      hi: 'टोक्यो महानगर',
      tr: 'Tokyo Metropolü',
      'pt-br': 'Metrópole de Tóquio'
    }
  },
  {
    code: 'kanagawa',
    region: 'kanto',
    names: {
      ja: '神奈川県',
      en: 'Kanagawa Prefecture',
      'zh-cn': '神奈川县',
      'zh-tw': '神奈川縣',
      ko: '가나가와현',
      th: 'จังหวัดคานางาวะ',
      vi: 'Tỉnh Kanagawa',
      id: 'Prefektur Kanagawa',
      ms: 'Wilayah Kanagawa',
      tl: 'Prepektura ng Kanagawa',
      fr: 'Préfecture de Kanagawa',
      de: 'Präfektur Kanagawa',
      es: 'Prefectura de Kanagawa',
      it: 'Prefettura di Kanagawa',
      pt: 'Prefeitura de Kanagawa',
      ru: 'Префектура Канагава',
      ar: 'محافظة كاناغاوا',
      hi: 'कानागावा प्रान्त',
      tr: 'Kanagawa Eyaleti',
      'pt-br': 'Prefeitura de Kanagawa'
    }
  },

  // 中部地方 (Chubu Region)
  {
    code: 'niigata',
    region: 'chubu',
    names: {
      ja: '新潟県',
      en: 'Niigata Prefecture',
      'zh-cn': '新潟县',
      'zh-tw': '新潟縣',
      ko: '니가타현',
      th: 'จังหวัดนีงาตะ',
      vi: 'Tỉnh Niigata',
      id: 'Prefektur Niigata',
      ms: 'Wilayah Niigata',
      tl: 'Prepektura ng Niigata',
      fr: 'Préfecture de Niigata',
      de: 'Präfektur Niigata',
      es: 'Prefectura de Niigata',
      it: 'Prefettura di Niigata',
      pt: 'Prefeitura de Niigata',
      ru: 'Префектура Ниигата',
      ar: 'محافظة نييغاتا',
      hi: 'नीगाता प्रान्त',
      tr: 'Niigata Eyaleti',
      'pt-br': 'Prefeitura de Niigata'
    }
  },
  {
    code: 'toyama',
    region: 'chubu',
    names: {
      ja: '富山県',
      en: 'Toyama Prefecture',
      'zh-cn': '富山县',
      'zh-tw': '富山縣',
      ko: '도야마현',
      th: 'จังหวัดโทยามะ',
      vi: 'Tỉnh Toyama',
      id: 'Prefektur Toyama',
      ms: 'Wilayah Toyama',
      tl: 'Prepektura ng Toyama',
      fr: 'Préfecture de Toyama',
      de: 'Präfektur Toyama',
      es: 'Prefectura de Toyama',
      it: 'Prefettura di Toyama',
      pt: 'Prefeitura de Toyama',
      ru: 'Префектура Тояма',
      ar: 'محافظة تويا',
      hi: 'तोयामा प्रान्त',
      tr: 'Toyama Eyaleti',
      'pt-br': 'Prefeitura de Toyama'
    }
  },
  {
    code: 'ishikawa',
    region: 'chubu',
    names: {
      ja: '石川県',
      en: 'Ishikawa Prefecture',
      'zh-cn': '石川县',
      'zh-tw': '石川縣',
      ko: '이시카와현',
      th: 'จังหวัดอิชิกาวะ',
      vi: 'Tỉnh Ishikawa',
      id: 'Prefektur Ishikawa',
      ms: 'Wilayah Ishikawa',
      tl: 'Prepektura ng Ishikawa',
      fr: 'Préfecture d\'Ishikawa',
      de: 'Präfektur Ishikawa',
      es: 'Prefectura de Ishikawa',
      it: 'Prefettura di Ishikawa',
      pt: 'Prefeitura de Ishikawa',
      ru: 'Префектура Исикава',
      ar: 'محافظة إيشيكاوا',
      hi: 'इशिकावा प्रान्त',
      tr: 'Ishikawa Eyaleti',
      'pt-br': 'Prefeitura de Ishikawa'
    }
  },
  {
    code: 'fukui',
    region: 'chubu',
    names: {
      ja: '福井県',
      en: 'Fukui Prefecture',
      'zh-cn': '福井县',
      'zh-tw': '福井縣',
      ko: '후쿠이현',
      th: 'จังหวัดฟุคุอิ',
      vi: 'Tỉnh Fukui',
      id: 'Prefektur Fukui',
      ms: 'Wilayah Fukui',
      tl: 'Prepektura ng Fukui',
      fr: 'Préfecture de Fukui',
      de: 'Präfektur Fukui',
      es: 'Prefectura de Fukui',
      it: 'Prefettura di Fukui',
      pt: 'Prefeitura de Fukui',
      ru: 'Префектура Фукуи',
      ar: 'محافظة فوكوي',
      hi: 'फुकुई प्रान्त',
      tr: 'Fukui Eyaleti',
      'pt-br': 'Prefeitura de Fukui'
    }
  },
  {
    code: 'yamanashi',
    region: 'chubu',
    names: {
      ja: '山梨県',
      en: 'Yamanashi Prefecture',
      'zh-cn': '山梨县',
      'zh-tw': '山梨縣',
      ko: '야마나시현',
      th: 'จังหวัดยามานาชิ',
      vi: 'Tỉnh Yamanashi',
      id: 'Prefektur Yamanashi',
      ms: 'Wilayah Yamanashi',
      tl: 'Prepektura ng Yamanashi',
      fr: 'Préfecture de Yamanashi',
      de: 'Präfektur Yamanashi',
      es: 'Prefectura de Yamanashi',
      it: 'Prefettura di Yamanashi',
      pt: 'Prefeitura de Yamanashi',
      ru: 'Префектура Яманаси',
      ar: 'محافظة ياماناشي',
      hi: 'यामानाशी प्रान्त',
      tr: 'Yamanashi Eyaleti',
      'pt-br': 'Prefeitura de Yamanashi'
    }
  },
  {
    code: 'nagano',
    region: 'chubu',
    names: {
      ja: '長野県',
      en: 'Nagano Prefecture',
      'zh-cn': '长野县',
      'zh-tw': '長野縣',
      ko: '나가노현',
      th: 'จังหวัดนางาโนะ',
      vi: 'Tỉnh Nagano',
      id: 'Prefektur Nagano',
      ms: 'Wilayah Nagano',
      tl: 'Prepektura ng Nagano',
      fr: 'Préfecture de Nagano',
      de: 'Präfektur Nagano',
      es: 'Prefectura de Nagano',
      it: 'Prefettura di Nagano',
      pt: 'Prefeitura de Nagano',
      ru: 'Префектура Нагано',
      ar: 'محافظة ناغانو',
      hi: 'नागानो प्रान्त',
      tr: 'Nagano Eyaleti',
      'pt-br': 'Prefeitura de Nagano'
    }
  },
  {
    code: 'gifu',
    region: 'chubu',
    names: {
      ja: '岐阜県',
      en: 'Gifu Prefecture',
      'zh-cn': '岐阜县',
      'zh-tw': '岐阜縣',
      ko: '기후현',
      th: 'จังหวัดกิฟุ',
      vi: 'Tỉnh Gifu',
      id: 'Prefektur Gifu',
      ms: 'Wilayah Gifu',
      tl: 'Prepektura ng Gifu',
      fr: 'Préfecture de Gifu',
      de: 'Präfektur Gifu',
      es: 'Prefectura de Gifu',
      it: 'Prefettura di Gifu',
      pt: 'Prefeitura de Gifu',
      ru: 'Префектура Гифу',
      ar: 'محافظة غيفو',
      hi: 'गिफू प्रान्त',
      tr: 'Gifu Eyaleti',
      'pt-br': 'Prefeitura de Gifu'
    }
  },
  {
    code: 'shizuoka',
    region: 'chubu',
    names: {
      ja: '静岡県',
      en: 'Shizuoka Prefecture',
      'zh-cn': '静冈县',
      'zh-tw': '靜岡縣',
      ko: '시즈오카현',
      th: 'จังหวัดชิซุโอกะ',
      vi: 'Tỉnh Shizuoka',
      id: 'Prefektur Shizuoka',
      ms: 'Wilayah Shizuoka',
      tl: 'Prepektura ng Shizuoka',
      fr: 'Préfecture de Shizuoka',
      de: 'Präfektur Shizuoka',
      es: 'Prefectura de Shizuoka',
      it: 'Prefettura di Shizuoka',
      pt: 'Prefeitura de Shizuoka',
      ru: 'Префектура Сидзуока',
      ar: 'محافظة شيزوكا',
      hi: 'शिज़ुओका प्रान्त',
      tr: 'Shizuoka Eyaleti',
      'pt-br': 'Prefeitura de Shizuoka'
    }
  },
  {
    code: 'aichi',
    region: 'chubu',
    names: {
      ja: '愛知県',
      en: 'Aichi Prefecture',
      'zh-cn': '爱知县',
      'zh-tw': '愛知縣',
      ko: '아이치현',
      th: 'จังหวัดไอชิ',
      vi: 'Tỉnh Aichi',
      id: 'Prefektur Aichi',
      ms: 'Wilayah Aichi',
      tl: 'Prepektura ng Aichi',
      fr: 'Préfecture d\'Aichi',
      de: 'Präfektur Aichi',
      es: 'Prefectura de Aichi',
      it: 'Prefettura di Aichi',
      pt: 'Prefeitura de Aichi',
      ru: 'Префектура Аити',
      ar: 'محافظة أيتشي',
      hi: 'आइची प्रान्त',
      tr: 'Aichi Eyaleti',
      'pt-br': 'Prefeitura de Aichi'
    }
  },

  // 近畿地方 (Kansai/Kinki Region)
  {
    code: 'mie',
    region: 'kansai',
    names: {
      ja: '三重県',
      en: 'Mie Prefecture',
      'zh-cn': '三重县',
      'zh-tw': '三重縣',
      ko: '미에현',
      th: 'จังหวัดมิเอะ',
      vi: 'Tỉnh Mie',
      id: 'Prefektur Mie',
      ms: 'Wilayah Mie',
      tl: 'Prepektura ng Mie',
      fr: 'Préfecture de Mie',
      de: 'Präfektur Mie',
      es: 'Prefectura de Mie',
      it: 'Prefettura di Mie',
      pt: 'Prefeitura de Mie',
      ru: 'Префектура Мие',
      ar: 'محافظة مي',
      hi: 'मी प्रान्त',
      tr: 'Mie Eyaleti',
      'pt-br': 'Prefeitura de Mie'
    }
  },
  {
    code: 'shiga',
    region: 'kansai',
    names: {
      ja: '滋賀県',
      en: 'Shiga Prefecture',
      'zh-cn': '滋贺县',
      'zh-tw': '滋賀縣',
      ko: '시가현',
      th: 'จังหวัดชิงะ',
      vi: 'Tỉnh Shiga',
      id: 'Prefektur Shiga',
      ms: 'Wilayah Shiga',
      tl: 'Prepektura ng Shiga',
      fr: 'Préfecture de Shiga',
      de: 'Präfektur Shiga',
      es: 'Prefectura de Shiga',
      it: 'Prefettura di Shiga',
      pt: 'Prefeitura de Shiga',
      ru: 'Префектура Сига',
      ar: 'محافظة شيغا',
      hi: 'शिगा प्रान्त',
      tr: 'Shiga Eyaleti',
      'pt-br': 'Prefeitura de Shiga'
    }
  },
  {
    code: 'kyoto',
    region: 'kansai',
    names: {
      ja: '京都府',
      en: 'Kyoto Prefecture',
      'zh-cn': '京都府',
      'zh-tw': '京都府',
      ko: '교토부',
      th: 'จังหวัดเกียวโต',
      vi: 'Phủ Kyoto',
      id: 'Prefektur Kyoto',
      ms: 'Wilayah Kyoto',
      tl: 'Prepektura ng Kyoto',
      fr: 'Préfecture de Kyoto',
      de: 'Präfektur Kyoto',
      es: 'Prefectura de Kioto',
      it: 'Prefettura di Kyoto',
      pt: 'Prefeitura de Quioto',
      ru: 'Префектура Киото',
      ar: 'محافظة كيوتو',
      hi: 'क्योटो प्रान्त',
      tr: 'Kyoto Eyaleti',
      'pt-br': 'Prefeitura de Quioto'
    }
  },
  {
    code: 'osaka',
    region: 'kansai',
    names: {
      ja: '大阪府',
      en: 'Osaka Prefecture',
      'zh-cn': '大阪府',
      'zh-tw': '大阪府',
      ko: '오사카부',
      th: 'จังหวัดโอซากะ',
      vi: 'Phủ Osaka',
      id: 'Prefektur Osaka',
      ms: 'Wilayah Osaka',
      tl: 'Prepektura ng Osaka',
      fr: 'Préfecture d\'Osaka',
      de: 'Präfektur Osaka',
      es: 'Prefectura de Osaka',
      it: 'Prefettura di Osaka',
      pt: 'Prefeitura de Osaka',
      ru: 'Префектура Осака',
      ar: 'محافظة أوساكا',
      hi: 'ओसाका प्रान्त',
      tr: 'Osaka Eyaleti',
      'pt-br': 'Prefeitura de Osaka'
    }
  },
  {
    code: 'hyogo',
    region: 'kansai',
    names: {
      ja: '兵庫県',
      en: 'Hyogo Prefecture',
      'zh-cn': '兵库县',
      'zh-tw': '兵庫縣',
      ko: '효고현',
      th: 'จังหวัดเฮียวโกะ',
      vi: 'Tỉnh Hyogo',
      id: 'Prefektur Hyogo',
      ms: 'Wilayah Hyogo',
      tl: 'Prepektura ng Hyogo',
      fr: 'Préfecture de Hyogo',
      de: 'Präfektur Hyogo',
      es: 'Prefectura de Hyogo',
      it: 'Prefettura di Hyogo',
      pt: 'Prefeitura de Hyogo',
      ru: 'Префектура Хёго',
      ar: 'محافظة هيوغو',
      hi: 'ह्योगो प्रान्त',
      tr: 'Hyogo Eyaleti',
      'pt-br': 'Prefeitura de Hyogo'
    }
  },
  {
    code: 'nara',
    region: 'kansai',
    names: {
      ja: '奈良県',
      en: 'Nara Prefecture',
      'zh-cn': '奈良县',
      'zh-tw': '奈良縣',
      ko: '나라현',
      th: 'จังหวัดนารา',
      vi: 'Tỉnh Nara',
      id: 'Prefektur Nara',
      ms: 'Wilayah Nara',
      tl: 'Prepektura ng Nara',
      fr: 'Préfecture de Nara',
      de: 'Präfektur Nara',
      es: 'Prefectura de Nara',
      it: 'Prefettura di Nara',
      pt: 'Prefeitura de Nara',
      ru: 'Префектура Нара',
      ar: 'محافظة نارا',
      hi: 'नारा प्रान्त',
      tr: 'Nara Eyaleti',
      'pt-br': 'Prefeitura de Nara'
    }
  },
  {
    code: 'wakayama',
    region: 'kansai',
    names: {
      ja: '和歌山県',
      en: 'Wakayama Prefecture',
      'zh-cn': '和歌山县',
      'zh-tw': '和歌山縣',
      ko: '와카야마현',
      th: 'จังหวัดวากายามะ',
      vi: 'Tỉnh Wakayama',
      id: 'Prefektur Wakayama',
      ms: 'Wilayah Wakayama',
      tl: 'Prepektura ng Wakayama',
      fr: 'Préfecture de Wakayama',
      de: 'Präfektur Wakayama',
      es: 'Prefectura de Wakayama',
      it: 'Prefettura di Wakayama',
      pt: 'Prefeitura de Wakayama',
      ru: 'Префектура Вакаяма',
      ar: 'محافظة واكاياما',
      hi: 'वकायामा प्रान्त',
      tr: 'Wakayama Eyaleti',
      'pt-br': 'Prefeitura de Wakayama'
    }
  },

  // 中国地方 (Chugoku Region)
  {
    code: 'tottori',
    region: 'chugoku',
    names: {
      ja: '鳥取県',
      en: 'Tottori Prefecture',
      'zh-cn': '鸟取县',
      'zh-tw': '鳥取縣',
      ko: '돗토리현',
      th: 'จังหวัดทอตโทะริ',
      vi: 'Tỉnh Tottori',
      id: 'Prefektur Tottori',
      ms: 'Wilayah Tottori',
      tl: 'Prepektura ng Tottori',
      fr: 'Préfecture de Tottori',
      de: 'Präfektur Tottori',
      es: 'Prefectura de Tottori',
      it: 'Prefettura di Tottori',
      pt: 'Prefeitura de Tottori',
      ru: 'Префектура Тоттори',
      ar: 'محافظة توتوري',
      hi: 'तोत्तोरी प्रान्त',
      tr: 'Tottori Eyaleti',
      'pt-br': 'Prefeitura de Tottori'
    }
  },
  {
    code: 'shimane',
    region: 'chugoku',
    names: {
      ja: '島根県',
      en: 'Shimane Prefecture',
      'zh-cn': '岛根县',
      'zh-tw': '島根縣',
      ko: '시마네현',
      th: 'จังหวัดชิมาเนะ',
      vi: 'Tỉnh Shimane',
      id: 'Prefektur Shimane',
      ms: 'Wilayah Shimane',
      tl: 'Prepektura ng Shimane',
      fr: 'Préfecture de Shimane',
      de: 'Präfektur Shimane',
      es: 'Prefectura de Shimane',
      it: 'Prefettura di Shimane',
      pt: 'Prefeitura de Shimane',
      ru: 'Префектура Симане',
      ar: 'محافظة شيمانه',
      hi: 'शिमाने प्रान्त',
      tr: 'Shimane Eyaleti',
      'pt-br': 'Prefeitura de Shimane'
    }
  },
  {
    code: 'okayama',
    region: 'chugoku',
    names: {
      ja: '岡山県',
      en: 'Okayama Prefecture',
      'zh-cn': '冈山县',
      'zh-tw': '岡山縣',
      ko: '오카야마현',
      th: 'จังหวัดโอกายามะ',
      vi: 'Tỉnh Okayama',
      id: 'Prefektur Okayama',
      ms: 'Wilayah Okayama',
      tl: 'Prepektura ng Okayama',
      fr: 'Préfecture d\'Okayama',
      de: 'Präfektur Okayama',
      es: 'Prefectura de Okayama',
      it: 'Prefettura di Okayama',
      pt: 'Prefeitura de Okayama',
      ru: 'Префектура Окаяма',
      ar: 'محافظة أوكاياما',
      hi: 'ओकायामा प्रान्त',
      tr: 'Okayama Eyaleti',
      'pt-br': 'Prefeitura de Okayama'
    }
  },
  {
    code: 'hiroshima',
    region: 'chugoku',
    names: {
      ja: '広島県',
      en: 'Hiroshima Prefecture',
      'zh-cn': '广岛县',
      'zh-tw': '廣島縣',
      ko: '히로시마현',
      th: 'จังหวัดฮิโรชิมะ',
      vi: 'Tỉnh Hiroshima',
      id: 'Prefektur Hiroshima',
      ms: 'Wilayah Hiroshima',
      tl: 'Prepektura ng Hiroshima',
      fr: 'Préfecture d\'Hiroshima',
      de: 'Präfektur Hiroshima',
      es: 'Prefectura de Hiroshima',
      it: 'Prefettura di Hiroshima',
      pt: 'Prefeitura de Hiroshima',
      ru: 'Префектура Хиросима',
      ar: 'محافظة هيروشيما',
      hi: 'हिरोशिमा प्रान्त',
      tr: 'Hiroshima Eyaleti',
      'pt-br': 'Prefeitura de Hiroshima'
    }
  },
  {
    code: 'yamaguchi',
    region: 'chugoku',
    names: {
      ja: '山口県',
      en: 'Yamaguchi Prefecture',
      'zh-cn': '山口县',
      'zh-tw': '山口縣',
      ko: '야마구치현',
      th: 'จังหวัดยามากุชิ',
      vi: 'Tỉnh Yamaguchi',
      id: 'Prefektur Yamaguchi',
      ms: 'Wilayah Yamaguchi',
      tl: 'Prepektura ng Yamaguchi',
      fr: 'Préfecture de Yamaguchi',
      de: 'Präfektur Yamaguchi',
      es: 'Prefectura de Yamaguchi',
      it: 'Prefettura di Yamaguchi',
      pt: 'Prefeitura de Yamaguchi',
      ru: 'Префектура Ямагути',
      ar: 'محافظة ياماغوتشي',
      hi: 'यामागुची प्रान्त',
      tr: 'Yamaguchi Eyaleti',
      'pt-br': 'Prefeitura de Yamaguchi'
    }
  },

  // 四国地方 (Shikoku Region)
  {
    code: 'tokushima',
    region: 'shikoku',
    names: {
      ja: '徳島県',
      en: 'Tokushima Prefecture',
      'zh-cn': '德岛县',
      'zh-tw': '德島縣',
      ko: '도쿠시마현',
      th: 'จังหวัดโทคุชิมะ',
      vi: 'Tỉnh Tokushima',
      id: 'Prefektur Tokushima',
      ms: 'Wilayah Tokushima',
      tl: 'Prepektura ng Tokushima',
      fr: 'Préfecture de Tokushima',
      de: 'Präfektur Tokushima',
      es: 'Prefectura de Tokushima',
      it: 'Prefettura di Tokushima',
      pt: 'Prefeitura de Tokushima',
      ru: 'Префектура Токусима',
      ar: 'محافظة توكوشيما',
      hi: 'तोकुशिमा प्रान्त',
      tr: 'Tokushima Eyaleti',
      'pt-br': 'Prefeitura de Tokushima'
    }
  },
  {
    code: 'kagawa',
    region: 'shikoku',
    names: {
      ja: '香川県',
      en: 'Kagawa Prefecture',
      'zh-cn': '香川县',
      'zh-tw': '香川縣',
      ko: '카가와현',
      th: 'จังหวัดคากาวะ',
      vi: 'Tỉnh Kagawa',
      id: 'Prefektur Kagawa',
      ms: 'Wilayah Kagawa',
      tl: 'Prepektura ng Kagawa',
      fr: 'Préfecture de Kagawa',
      de: 'Präfektur Kagawa',
      es: 'Prefectura de Kagawa',
      it: 'Prefettura di Kagawa',
      pt: 'Prefeitura de Kagawa',
      ru: 'Префектура Кагава',
      ar: 'محافظة كاغاوا',
      hi: 'कागावा प्रान्त',
      tr: 'Kagawa Eyaleti',
      'pt-br': 'Prefeitura de Kagawa'
    }
  },
  {
    code: 'ehime',
    region: 'shikoku',
    names: {
      ja: '愛媛県',
      en: 'Ehime Prefecture',
      'zh-cn': '爱媛县',
      'zh-tw': '愛媛縣',
      ko: '에히메현',
      th: 'จังหวัดเอะฮิเมะ',
      vi: 'Tỉnh Ehime',
      id: 'Prefektur Ehime',
      ms: 'Wilayah Ehime',
      tl: 'Prepektura ng Ehime',
      fr: 'Préfecture d\'Ehime',
      de: 'Präfektur Ehime',
      es: 'Prefectura de Ehime',
      it: 'Prefettura di Ehime',
      pt: 'Prefeitura de Ehime',
      ru: 'Префектура Эхиме',
      ar: 'محافظة إهيمي',
      hi: 'एहिमे प्रान्त',
      tr: 'Ehime Eyaleti',
      'pt-br': 'Prefeitura de Ehime'
    }
  },
  {
    code: 'kochi',
    region: 'shikoku',
    names: {
      ja: '高知県',
      en: 'Kochi Prefecture',
      'zh-cn': '高知县',
      'zh-tw': '高知縣',
      ko: '고치현',
      th: 'จังหวัดโคชิ',
      vi: 'Tỉnh Kochi',
      id: 'Prefektur Kochi',
      ms: 'Wilayah Kochi',
      tl: 'Prepektura ng Kochi',
      fr: 'Préfecture de Kochi',
      de: 'Präfektur Kochi',
      es: 'Prefectura de Kochi',
      it: 'Prefettura di Kochi',
      pt: 'Prefeitura de Kochi',
      ru: 'Префектура Коти',
      ar: 'محافظة كوتشي',
      hi: 'कोची प्रान्त',
      tr: 'Kochi Eyaleti',
      'pt-br': 'Prefeitura de Kochi'
    }
  },

  // 九州地方 (Kyushu Region)
  {
    code: 'fukuoka',
    region: 'kyushu',
    names: {
      ja: '福岡県',
      en: 'Fukuoka Prefecture',
      'zh-cn': '福冈县',
      'zh-tw': '福岡縣',
      ko: '후쿠오카현',
      th: 'จังหวัดฟุกุโอกะ',
      vi: 'Tỉnh Fukuoka',
      id: 'Prefektur Fukuoka',
      ms: 'Wilayah Fukuoka',
      tl: 'Prepektura ng Fukuoka',
      fr: 'Préfecture de Fukuoka',
      de: 'Präfektur Fukuoka',
      es: 'Prefectura de Fukuoka',
      it: 'Prefettura di Fukuoka',
      pt: 'Prefeitura de Fukuoka',
      ru: 'Префектура Фукуока',
      ar: 'محافظة فوكوكا',
      hi: 'फुकुओका प्रान्त',
      tr: 'Fukuoka Eyaleti',
      'pt-br': 'Prefeitura de Fukuoka'
    }
  },
  {
    code: 'saga',
    region: 'kyushu',
    names: {
      ja: '佐賀県',
      en: 'Saga Prefecture',
      'zh-cn': '佐贺县',
      'zh-tw': '佐賀縣',
      ko: '사가현',
      th: 'จังหวัดสางะ',
      vi: 'Tỉnh Saga',
      id: 'Prefektur Saga',
      ms: 'Wilayah Saga',
      tl: 'Prepektura ng Saga',
      fr: 'Préfecture de Saga',
      de: 'Präfektur Saga',
      es: 'Prefectura de Saga',
      it: 'Prefettura di Saga',
      pt: 'Prefeitura de Saga',
      ru: 'Префектура Сага',
      ar: 'محافظة ساغا',
      hi: 'सागा प्रान्त',
      tr: 'Saga Eyaleti',
      'pt-br': 'Prefeitura de Saga'
    }
  },
  {
    code: 'nagasaki',
    region: 'kyushu',
    names: {
      ja: '長崎県',
      en: 'Nagasaki Prefecture',
      'zh-cn': '长崎县',
      'zh-tw': '長崎縣',
      ko: '나가사키현',
      th: 'จังหวัดนางาซากิ',
      vi: 'Tỉnh Nagasaki',
      id: 'Prefektur Nagasaki',
      ms: 'Wilayah Nagasaki',
      tl: 'Prepektura ng Nagasaki',
      fr: 'Préfecture de Nagasaki',
      de: 'Präfektur Nagasaki',
      es: 'Prefectura de Nagasaki',
      it: 'Prefettura di Nagasaki',
      pt: 'Prefeitura de Nagasaki',
      ru: 'Префектура Нагасаки',
      ar: 'محافظة ناغاساكي',
      hi: 'नागासाकी प्रान्त',
      tr: 'Nagasaki Eyaleti',
      'pt-br': 'Prefeitura de Nagasaki'
    }
  },
  {
    code: 'kumamoto',
    region: 'kyushu',
    names: {
      ja: '熊本県',
      en: 'Kumamoto Prefecture',
      'zh-cn': '熊本县',
      'zh-tw': '熊本縣',
      ko: '구마모토현',
      th: 'จังหวัดคุมาโมโตะ',
      vi: 'Tỉnh Kumamoto',
      id: 'Prefektur Kumamoto',
      ms: 'Wilayah Kumamoto',
      tl: 'Prepektura ng Kumamoto',
      fr: 'Préfecture de Kumamoto',
      de: 'Präfektur Kumamoto',
      es: 'Prefectura de Kumamoto',
      it: 'Prefettura di Kumamoto',
      pt: 'Prefeitura de Kumamoto',
      ru: 'Префектура Кумамото',
      ar: 'محافظة كوماموتو',
      hi: 'कुमामोतो प्रान्त',
      tr: 'Kumamoto Eyaleti',
      'pt-br': 'Prefeitura de Kumamoto'
    }
  },
  {
    code: 'oita',
    region: 'kyushu',
    names: {
      ja: '大分県',
      en: 'Oita Prefecture',
      'zh-cn': '大分县',
      'zh-tw': '大分縣',
      ko: '오이타현',
      th: 'จังหวัดโออิตะ',
      vi: 'Tỉnh Oita',
      id: 'Prefektur Oita',
      ms: 'Wilayah Oita',
      tl: 'Prepektura ng Oita',
      fr: 'Préfecture d\'Oita',
      de: 'Präfektur Oita',
      es: 'Prefectura de Oita',
      it: 'Prefettura di Oita',
      pt: 'Prefeitura de Oita',
      ru: 'Префектура Оита',
      ar: 'محافظة أويتا',
      hi: 'ओइता प्रान्त',
      tr: 'Oita Eyaleti',
      'pt-br': 'Prefeitura de Oita'
    }
  },
  {
    code: 'miyazaki',
    region: 'kyushu',
    names: {
      ja: '宮崎県',
      en: 'Miyazaki Prefecture',
      'zh-cn': '宫崎县',
      'zh-tw': '宮崎縣',
      ko: '미야자키현',
      th: 'จังหวัดมิยาซากิ',
      vi: 'Tỉnh Miyazaki',
      id: 'Prefektur Miyazaki',
      ms: 'Wilayah Miyazaki',
      tl: 'Prepektura ng Miyazaki',
      fr: 'Préfecture de Miyazaki',
      de: 'Präfektur Miyazaki',
      es: 'Prefectura de Miyazaki',
      it: 'Prefettura di Miyazaki',
      pt: 'Prefeitura de Miyazaki',
      ru: 'Префектура Миядзаки',
      ar: 'محافظة مياز',
      hi: 'मियाज़ाकी प्रान्त',
      tr: 'Miyazaki Eyaleti',
      'pt-br': 'Prefeitura de Miyazaki'
    }
  },
  {
    code: 'kagoshima',
    region: 'kyushu',
    names: {
      ja: '鹿児島県',
      en: 'Kagoshima Prefecture',
      'zh-cn': '鹿儿岛县',
      'zh-tw': '鹿兒島縣',
      ko: '가고시마현',
      th: 'จังหวัดคาโงชิมะ',
      vi: 'Tỉnh Kagoshima',
      id: 'Prefektur Kagoshima',
      ms: 'Wilayah Kagoshima',
      tl: 'Prepektura ng Kagoshima',
      fr: 'Préfecture de Kagoshima',
      de: 'Präfektur Kagoshima',
      es: 'Prefectura de Kagoshima',
      it: 'Prefettura di Kagoshima',
      pt: 'Prefeitura de Kagoshima',
      ru: 'Префектура Кагосима',
      ar: 'محافظة كاغوشيما',
      hi: 'कागोशिमा प्रान्त',
      tr: 'Kagoshima Eyaleti',
      'pt-br': 'Prefeitura de Kagoshima'
    }
  },

  // 沖縄地方 (Okinawa Region)
  {
    code: 'okinawa',
    region: 'okinawa',
    names: {
      ja: '沖縄県',
      en: 'Okinawa Prefecture',
      'zh-cn': '冲绳县',
      'zh-tw': '沖繩縣',
      ko: '오키나와현',
      th: 'จังหวัดโอกินาวะ',
      vi: 'Tỉnh Okinawa',
      id: 'Prefektur Okinawa',
      ms: 'Wilayah Okinawa',
      tl: 'Prepektura ng Okinawa',
      fr: 'Préfecture d\'Okinawa',
      de: 'Präfektur Okinawa',
      es: 'Prefectura de Okinawa',
      it: 'Prefettura di Okinawa',
      pt: 'Prefeitura de Okinawa',
      ru: 'Префектура Окинава',
      ar: 'محافظة أوكيناوا',
      hi: 'ओकिनावा प्रान्त',
      tr: 'Okinawa Eyaleti',
      'pt-br': 'Prefeitura de Okinawa'
    }
  }
];

// 都道府県名を言語別に取得
export function getPrefectureName(code: string, lang: string): string {
  const prefecture = ALL_PREFECTURES.find(p => p.code === code);
  return prefecture?.names[lang] || prefecture?.names['ja'] || code;
}

// 指定言語での全都道府県リストを取得
export function getPrefecturesForLanguage(lang: string) {
  return ALL_PREFECTURES.map(prefecture => ({
    code: prefecture.code,
    name: prefecture.names[lang] || prefecture.names['ja'],
    region: prefecture.region
  }));
}

// 地域別都道府県リストを取得
export function getPrefecturesByRegion(lang: string) {
  const regions: Record<string, typeof ALL_PREFECTURES> = {};
  
  ALL_PREFECTURES.forEach(prefecture => {
    if (!regions[prefecture.region]) {
      regions[prefecture.region] = [];
    }
    regions[prefecture.region].push(prefecture);
  });
  
  return regions;
}